### ISSUE TITLE
Margin on Transfer Page Columns

### ISSUE THREAD

**Issue by FallOfArca** [catppuccin/qbittorrent#13]
hi :3 Header says most of it. The column headers in the transfer tab have a margin on the right side, making them take up unnecessary space
![Screenshot 2024-06-08 145839](https://github.com/catppuccin/qbittorrent/assets/41400684/b335ae82-d78f-40d1-82e5-77372c946653)

**Comment by sgoudham** [comment]
Hey :wave:,
I don't think this is a concern of the theme because the default application has the same behaviour/look:

![image](https://github.com/user-attachments/assets/443c34f8-b42c-4706-89d7-4881cce88303)

You can drag the columns to fit whatever size screen you're on, e.g.

![image](https://github.com/user-attachments/assets/73746918-d659-438c-bef1-285657970acd)

Going to close this issue but feel free to re-open if you think I've misunderstood you.
